### ISSUE TITLE
Questions plz

### ISSUE THREAD

**Issue by mikek9084** [Teknasyon-Teknoloji/Getcontact-Bootcamp#22]
First this one of the best template on GitHub 
1. what are the benefits from covert all repositories functions to return flow<T>?
2. what is the purpose from channelFlow?
3. is it legal to To do ui navigation in the view model?

**Comment by alirezat775** [comment]
Hi there,

1. It is not mandatory to return flow for all repository functions, however, to achieve a reactive approach this is necessary,  
2. Using channel flow gives the power of channel (single emit), which is useful when we need fire-and-forget data and we can observe it like other flows
3. I'm not sure that I could understand the question, however, based on MVI, we can send an intent to the ViewModel, and the ViewModel is responsible for dispatching the intent based on the logic, it means the ViewModel is not a Navigation class it's a Delegation layer to send the UiAction from View to the Navigation class.
