### ISSUE TITLE
inquiry 

### ISSUE THREAD

**Issue by Zorodebug5** [Teknasyon-Teknoloji/Getcontact-Bootcamp#23]
thank you,
what if there are two features are using the same domain models ?

**Comment by alirezat775** [comment]
This is not recommended to share models between modules, however if you have a shared logic like model for remote config or feature flag, you can create plugin type module.
you can learn more from the below link

https://engineering.teknasyon.com/modularization-of-mobile-applications-at-scale-df57815ff19a

**Comment by Zorodebug5** [comment]
@alirezat775 thank you very much,
in my use case I want to shared the user object across the project after he signed in, because it is heavily used in the application screens , and I believe that should be a common use case , also the currency object is used everywhere in my shopping app.

that is why I want to share user object and currency object a cross the modules , do you think there is a better way to look at these types of issue , I am curious in your opinion?

**Comment by alirezat775** [comment]
@Zorodebug5, you're welcome,
In this case, plugin type is the best choice; 
you can create a user module as a plugin module, and for authentication, you can expose auth functions from this module and save data inside the module, it's best practice not to expose accessing data layer around the application, and all auth logic should be isolated inside of the user module
at the end expose a function for getting user data
mostly plugin modules expose functionality through the client classes.


```kotlin

class UserClient internal constructor(
    private userRepository: UserRepository
) {

    fun auth(username: String, password: String): Boolean {
        // implementation
    }

    fun user(): UserModel {
        return userRepository.getUser()
    }
}
```

and the UserRepository should be internal

```kotlin
internal interface UserRepository {
    fun auth(username: String, password: String): Boolean
    fun user(): UserModel
}
```

**Comment by Zorodebug5** [comment]
that is very kind from you 😃
